### ISSUE TITLE
Incorrect measurement circuit

### ISSUE THREAD

**Issue by daniel-miller-quantum** [teaguetomesh/vqe-term-grouping#1]
I believe there is a potential bug in `term_grouping.py`:

When I try to get the readout circuit for 'XXX' , 'ZZI', and 'IIX', I get the following circuit with 2 two-qubit gates.

![image](https://user-images.githubusercontent.com/72351187/139223647-5101cc53-e1cf-4b0f-88fb-f08413af91bb.png)

If I am not mistaken, this circuit does not measure 'IIX'.

**Comment by singular-value** [comment]
I think this circuit does look okay actually.
Basically, measurement of the bottom qubit (q_2) will report <IIX> on the input state.

A few examples to show it working:
* input state, correct <IIX>, quirk link
* |000>, 0 (50% on bottom qubit), https://algassert.com/quirk#circuit=%7B%22cols%22%3A%5B%5B1%2C%22H%22%5D%2C%5B%22%E2%80%A2%22%2C1%2C%22X%22%5D%2C%5B%22%E2%80%A2%22%2C%22Z%22%5D%2C%5B%22H%22%2C%22H%22%2C%22H%22%5D%5D%7D
* |00+>, 1 (0% on bottom qubit), https://algassert.com/quirk#circuit=%7B%22cols%22%3A%5B%5B1%2C%22H%22%5D%2C%5B%22%E2%80%A2%22%2C1%2C%22X%22%5D%2C%5B%22%E2%80%A2%22%2C%22Z%22%5D%2C%5B%22H%22%2C%22H%22%2C%22H%22%5D%5D%2C%22init%22%3A%5B0%2C0%2C%22%2B%22%5D%7D
* |00->, 0 (100% on bottom qubit), https://algassert.com/quirk#circuit=%7B%22cols%22%3A%5B%5B1%2C%22H%22%5D%2C%5B%22%E2%80%A2%22%2C1%2C%22X%22%5D%2C%5B%22%E2%80%A2%22%2C%22Z%22%5D%2C%5B%22H%22%2C%22H%22%2C%22H%22%5D%5D%2C%22init%22%3A%5B0%2C0%2C%22-%22%5D%7D
* |ii+>, 1 (0% on bottom qubit), https://algassert.com/quirk#circuit=%7B%22cols%22%3A%5B%5B1%2C%22H%22%5D%2C%5B%22%E2%80%A2%22%2C1%2C%22X%22%5D%2C%5B%22%E2%80%A2%22%2C%22Z%22%5D%2C%5B%22H%22%2C%22H%22%2C%22H%22%5D%5D%2C%22init%22%3A%5B%22i%22%2C%22i%22%2C%22%2B%22%5D%7D

So seems to be working (though feel free to make a PR for better documentation).

However, I do know that there can be a "sign error" for observables that have a Y. E.g., if you ask `get_GC_circuit` for something like YIX, it might actually give you a circuit that reports -YIX. Haven't gotten to the bottom of it yet--it can be fixed in post-processing 🤷‍♂️

**Comment by daniel-miller-quantum** [comment]
Hi Pranav,

indeed, you are right. It's my mistake, I forgot to put the Hadamard gates on both sides when turning the target of the CNOT into a CZ.

Sorry about the confusion.
